create table users
(
    id        int8 generated by default as identity,
    email     varchar(255),
    username  varchar(255),
    password  varchar(255),
    is_banned boolean not null,
    primary key (id)
);
