create table users
(
    id        int8 generated by default as identity,
    username  varchar(255),
    email     varchar(255),
    password  varchar(255),
    is_banned boolean,
    primary key (id)
);