create table users
(
    id                    int8 generated by default as identity,
    username              varchar(255) unique,
    email                 varchar(255) unique,
    password              varchar(255),
    is_account_non_locked boolean,
    primary key (id)
);