inputFileUpload:
  path: C:\Users\Антон\Desktop\test\lab3\input.txt
encryptedFileUpload:
  path: C:\Users\Антон\IdeaProjects\trash\uploads\encrypted
decryptedFileUpload:
  path: C:\Users\Антон\IdeaProjects\trash\uploads\decrypted
spring:
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB