inputFileUpload:
  path: C:\Users\Антон\IdeaProjects\test\lab3\input.txt
encryptedFileUpload:
  path: C:\Users\Антон\IdeaProjects\trash\uploads\encrypted
decryptedFileUpload:
  path: C:\Users\Антон\IdeaProjects\trash\uploads\decrypted
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB